rvm: "1.9.2"
before_install:
  - git submodule update --init --recursive
  - ruby --version
  - gem --version
  - rvm --version
  - bundle install

script: "rake"

language: node_js

node_js:
  - "0.10"
  - "0.8"
  - "0.6"

notifications:
  email:
    - jb@jbpros.com
  irc:
    - "irc.freenode.org#cucumber"
